/**
 * Dashboard configuration
 * Auto-generated by scripts/update-dashboard-config.sh
 */
window.CRYPTO_MONITOR_CONFIG = {
  API_BASE_URL: "https://1qooisi34c.execute-api.ap-southeast-2.amazonaws.com/prod/"
};
