#!/bin/bash
# Script to update dashboard config.js with API Gateway URL after deployment

if [ -z "$1" ]; then
  echo "Usage: ./scripts/update-dashboard-config.sh <API_URL>"
  echo "Example: ./scripts/update-dashboard-config.sh https://abc123.execute-api.ap-southeast-2.amazonaws.com/prod/"
  exit 1
fi

API_URL="$1"

# Update config.js
cat > dashboard/config.js << EOF
/**
 * Dashboard configuration
 * Auto-generated by scripts/update-dashboard-config.sh
 */
window.CRYPTO_MONITOR_CONFIG = {
  API_BASE_URL: "${API_URL}"
};
EOF

echo "✅ Updated dashboard/config.js with API_BASE_URL: ${API_URL}"
echo ""
echo "Next steps:"
echo "1. Run 'npx cdk deploy' to deploy the updated dashboard to S3"
echo "2. Access your dashboard via the CloudFront URL from CDK output"
